[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true

[program:queue]
command=php /var/www/artisan queue:work redis --sleep=3 --tries=3
autostart=true
autorestart=true

[program:scheduler]
command=php /var/www/artisan schedule:work
autostart=true
autorestart=true

[program:polling]
command=bash -c "while true; do php /var/www/artisan app:telegram-polling; sleep 1; done"
autostart=true
autorestart=true
